create database fangchan;
use fangchan;
# yuangong version1, for test only, needs modify
create table yuangong (yuangongbianhao int, xingbie varchar(2), yuangongxingming varchar(4), xueli varchar(2), shenfenzhenghao varchar(18), hunyinzhuangkuang varchar(2), lianxidianhua varchar(13), chushengriqi date, jiguan varchar(6), jiuzhiriqi date, suozaiquanxianzu varchar(6), mima varchar(20), zhuzhi varchar(10), beizhu varchar(20));
insert into yuangong values(1, '男', '测试姓名', '博士', '123456789012345678', '单身', '1234567890123', '2000-1-1', '火星', '2001-8-30', '超级用户', 'passwd', '火星研究所', 'book of mozilla');

create table canshu_fangkelaiyuan (bianhao int, mingcheng varchar(4));
insert into canshu_fangkelaiyuan values (1, '来访');
insert into canshu_fangkelaiyuan values (2, '来电');
insert into canshu_fangkelaiyuan values (3, '介绍');
insert into canshu_fangkelaiyuan values (4, '网络');
create table canshu_fangyuanzhuangtai (bianhao int, mingcheng varchar(4));
insert into canshu_fangyuanzhuangtai values (1, '正常状态');
insert into canshu_fangyuanzhuangtai values (2, '已经成交');
insert into canshu_fangyuanzhuangtai values (3, '保留状态');
insert into canshu_fangyuanzhuangtai values (4, '已经失效');
create table canshu_kehuzhuangtai(bianhao int, mingcheng varchar(4));
insert into canshu_kehuzhuangtai values (1, '有效客户');
insert into canshu_kehuzhuangtai values (2, '潜在客户');
insert into canshu_kehuzhuangtai values (3, '已签约');
insert into canshu_kehuzhuangtai values (4, '已失效');
create table canshu_genjinfangshi(bianhao int, mingcheng varchar(4));
insert into canshu_genjinfangshi values (1, '电话');
insert into canshu_genjinfangshi values (2, '短信');
insert into canshu_genjinfangshi values (3, '拜访');
insert into canshu_genjinfangshi values (4, '来访');
create table canshu_fukuanfangshi(bianhao int, mingcheng varchar(4));
insert into canshu_fukuanfangshi values (1, '现金');
insert into canshu_fukuanfangshi values (2, '支票');
insert into canshu_fukuanfangshi values (3, '转帐');
create table canshu_fenchengshuoming(binahao int, mingcheng varchar(4));
insert into canshu_fenchengshuoming values (1, '开发分成');
insert into canshu_fenchengshuoming values (2, '跟进分成');
insert into canshu_fenchengshuoming values (3, '签约分成');
create table canshu_chengqu(bianhao int, mingcheng varchar(4));
insert into canshu_chengqu values (1, '东城区');
insert into canshu_chengqu values (2, '西城区');
insert into canshu_chengqu values (3, '崇文区');
insert into canshu_chengqu values (4, '宣武区');
insert into canshu_chengqu values (5, '朝阳区');
insert into canshu_chengqu values (6, '丰台区');
insert into canshu_chengqu values (7, '石景山区');
insert into canshu_chengqu values (8, '海淀区');
insert into canshu_chengqu values (9, '门头沟区');
insert into canshu_chengqu values (10, '房山区');
create table quanxianzu(mingcheng varchar(4), chushoufangyuan bool, chuzufangyuan bool, hezufangyuan bool, qiugoukehu bool, qiuzukehu bool, hezukehu bool, fangyuangenjin bool, keyuangenjin bool, qianyueguanli bool, yuangongguanli bool, quanxianzushezhi bool, canshushezhi bool);
insert into quanxianzu values('超级用户', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into quanxianzu values('店长', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0);
insert into quanxianzu values('分片经理', 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0);
create table chuzufangyuan (fangwubianhao int primary key, dangqianzhuangtai varchar(8), zhiyeguwen varchar(4), fangwulaiyuan varchar(4), suozaichengqu varchar(6), fangwujiage int, fangwuleixing varchar(6) , chanquan varchar(6), fangwumianji float, jiancheniandai int, suozailouceng int, zhuangxiubiaozhun varchar(6), loucengzongshu int, jutidizhi varchar(10), chufang bool, chuang bool, jiaju bool, youxiandianshi bool, kuaidaiwang bool, dianhua bool, reshuiqi bool, dianshiji bool, kongtiao bool, xiyiji bool, bingxiang bool, meiqi bool, nuanqi bool, qicheku bool, fangyuanxiangxixinxi varchar(20), yezhuxingming varchar(4), lianxidianhua varchar(14), lianxishouji varchar(11), yezhushuoming varchar(1));
create table chushoufangyuan (fangwubianhao int primary key, dangqianzhuangtai varchar(8), zhiyeguwen varchar(4), fangwulaiyuan varchar(4), suozaichengqu varchar(6), fangwujiage int, fangwuleixing varchar(6) , chanquan varchar(6), fangwumianji float, jiancheniandai int, suozailouceng int, zhuangxiubiaozhun varchar(6), loucengzongshu int, jutidizhi varchar(10), chufang bool, chuang bool, jiaju bool, youxiandianshi bool, kuaidaiwang bool, dianhua bool, reshuiqi bool, dianshiji bool, kongtiao bool, xiyiji bool, bingxiang bool, meiqi bool, nuanqi bool, qicheku bool, fangyuanxiangxixinxi varchar(20), yezhuxingming varchar(4), lianxidianhua varchar(14), lianxishouji varchar(11), yezhushuoming varchar(1));
create table hezufangyuan (fangwubianhao int primary key,  dangqianzhuangtai varchar(8), zhiyeguwen varchar(4), fangwulaiyuan varchar(4), suozaichengqu varchar(6), fangwujiage int, fangwuleixing varchar(6) , xingbieqingxiang varchar(6), fangwumianji float, jiancheniandai int, suozailouceng int, zhuangxiubiaozhun varchar(6), loucengzongshu int, jutidizhi varchar(10), chufang bool, chuang bool, jiaju bool, youxiandianshi bool, kuaidaiwang bool, dianhua bool, reshuiqi bool, dianshiji bool, kongtiao bool, xiyiji bool, bingxiang bool, meiqi bool, nuanqi bool, qicheku bool, fangyuanxiangxixinxi varchar(20), yezhuxingming varchar(4), lianxidianhua varchar(14), lianxishouji varchar(11), yezhushuoming varchar(1));

create table qiugoukehu (kehubianhao int primary key, dangqianzhuangtai varchar(8), zhiyeguwen varchar(4), kehulaiyuan varchar(4), suozaichengqu varchar(6), fangwujiage int, fangwuleixing varchar(6), chanquan varchar(6), fangwumianji float, xinjiuchengdu varchar(4), suozailouceng int, zhuangxiubiaozhun varchar(6), loucengzongshu int, yixiangdizhi varchar(10), chufang bool, chuang bool, jiaju bool, youxiandianshi bool, kuaidaiwang bool, dianhua bool, reshuiqi bool, dianshiji bool, kongtiao bool, xiyiji bool, bingxiang bool, meiqi bool, nuanqi bool, qicheku bool, fangyuanxiangxixinxi varchar(20), yezhuxingming varchar(4), lianxidianhua varchar(14), lianxishouji varchar(11), yezhushuoming varchar(1));
create table qiuzukehu (kehubianhao int primary key, dangqianzhuangtai varchar(8), zhiyeguwen varchar(4), kehulaiyuan varchar(4), suozaichengqu varchar(6), fangwujiage int, fangwuleixing varchar(6), chanquan varchar(6), fangwumianji float, xinjiuchengdu varchar(4), suozailouceng int, zhuangxiubiaozhun varchar(6), loucengzongshu int, yixiangdizhi varchar(10), chufang bool, chuang bool, jiaju bool, youxiandianshi bool, kuaidaiwang bool, dianhua bool, reshuiqi bool, dianshiji bool, kongtiao bool, xiyiji bool, bingxiang bool, meiqi bool, nuanqi bool, qicheku bool, fangyuanxiangxixinxi varchar(20), yezhuxingming varchar(4), lianxidianhua varchar(14), lianxishouji varchar(11), yezhushuoming varchar(1));
create table hezukehu (kehubianhao int primary key, dangqianzhuangtai varchar(8), zhiyeguwen varchar(4), kehulaiyuan varchar(4), suozaichengqu varchar(6), fangwujiage int, fangwuleixing varchar(6), xingbieqingxiang varchar(6), fangwumianji float, xinjiuchengdu varchar(4), suozailouceng int, zhuangxiubiaozhun varchar(6), loucengzongshu int, yixiangdizhi varchar(10), chufang bool, chuang bool, jiaju bool, youxiandianshi bool, kuaidaiwang bool, dianhua bool, reshuiqi bool, dianshiji bool, kongtiao bool, xiyiji bool, bingxiang bool, meiqi bool, nuanqi bool, qicheku bool, fangyuanxiangxixinxi varchar(20), yezhuxingming varchar(4), lianxidianhua varchar(14), lianxishouji varchar(11), yezhushuoming varchar(1));

create table qianyue (fangyuan varchar(4), kehu varchar(4), yuanggong varchar(4), yongjin int, tichengfangshi varchar(4), bianhao int primary key);
